site_name: aiTour
site_author: Kinnariya Mama Tanha
site_url: https://aitour.icu/
site_description: >-
  AI学习之旅
repo_url: https://github.com/KinnariyaMamaTanha/aiTour/
repo_name: aiTour

theme:
  name: material
  language: zh
  
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    # For dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # For the light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


  font:
    text: Roboto
    code: Roboto Mono
  
  favicon: images/logo.jpg

  icon:
    repo: fontawesome/brands/git-alt
  
  static_templates:
    - 404.html

nav:
  - 序: index.md
  - 旅途前的准备: preparations.md
  - 我的学习规划: learning-path.md
  - 大一上:
    - 微积分(1): da-yi-shang/calculus-1.md
    - 线性代数: da-yi-shang/linear-algebra.md
    - 离散数学入门: da-yi-shang/discrete-math.md
    - C++: da-yi-shang/c++.md
    - Python: da-yi-shang/python.md
    - 实用工具:
      - Git: tools/Git.md
      - Vim: tools/Vim.md
      - Anaconda: tools/Anaconda.md
      - Obsidian: tools/Obsidian.md
      - Scoop: tools/Scoop.md
      - Material-for-MkDocs: tools/Material-for-MkDocs.md
      - 魔法: tools/Magic.md
  - 大一寒假:
    - 数据结构: da-yi-han-jia/data-structure.md
    - 算法设计与分析: da-yi-han-jia/algorithm.md
    - 数据分析: da-yi-han-jia/data-analysis.md
    - 实用工具:
      - WSL2: tools/WSL2.md
  - 大一下:
    - 微积分(2): da-yi-xia/calculus-2.md
    - 概率论: da-yi-xia/probability.md
    - 机器学习入门: da-yi-xia/machine-learning.md
    - 深度学习入门: da-yi-xia/deep-learning.md
    - 实用工具:
      - Latex: tools/Latex.md
      - Docker: tools/Docker.md
  - 大一暑假:
    - 凸优化: da-yi-shu-jia/convex-optimization.md
    - 矩阵论: da-yi-shu-jia/matrix-theory.md
    - 计算机系统入门: da-yi-shu-jia/computer-system.md
  - 小工具: tools/gadgets.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KinnariyaMamaTanha
      name: My GitHub Account
    - icon: fontawesome/solid/paper-plane
      link: mailto:yuhengji073@gmail.com
      name: My E-mail Address

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - abbr
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2023 - present KinnariyaMamaTanha
